# https://stackoverflow.com/a/41916657/122441
dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - cmake

script:
  # https://tuannguyen68.gitbooks.io/learning-cmake-a-beginner-s-guide/content/chap1/chap1.html
  # create CMake configuration files inside folder build
  - cmake -H. -Bbuild
  # generate the output program hello in bin folder
  - cmake --build build -- -j3
