# https://stackoverflow.com/a/41916657/122441
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      # CMake 3.x : https://askubuntu.com/a/610352/11666
      - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
      - cmake

script:
  # https://tuannguyen68.gitbooks.io/learning-cmake-a-beginner-s-guide/content/chap1/chap1.html
  # create CMake configuration files inside folder build
  - cmake -H. -Bbuild
  # generate the output program hello in bin folder
  - cmake --build build -- -j3
  - bin/main < test01.txt
